/**
 * Tablet Deployment Script
 *
 * Automates the process of deploying the app for tablet testing:
 * 1. Detects your local IP address
 * 2. Updates .env.production with the correct proxy URL
 * 3. Builds the production version
 * 4. Provides instructions for running servers
 */

import { networkInterfaces } from 'os';
import { writeFileSync, readFileSync } from 'fs';
import { execSync } from 'child_process';

console.log('\n🚀 SmartCookBook - Tablet Deployment Script\n');
console.log('='.repeat(50));

// Step 1: Detect local IP address
function getLocalIP() {
  const nets = networkInterfaces();
  const results = [];

  for (const name of Object.keys(nets)) {
    for (const net of nets[name]) {
      // Skip internal (loopback) and non-IPv4 addresses
      const familyV4Value = typeof net.family === 'string' ? 'IPv4' : 4;
      if (net.family === familyV4Value && !net.internal) {
        results.push({
          name: name,
          address: net.address
        });
      }
    }
  }

  return results;
}

const localIPs = getLocalIP();

console.log('\n📡 Detected Network Interfaces:');
localIPs.forEach((ip, index) => {
  console.log(`   ${index + 1}. ${ip.name}: ${ip.address}`);
});

if (localIPs.length === 0) {
  console.error('\n❌ Error: No network interfaces found!');
  console.error('   Make sure you are connected to a network.');
  process.exit(1);
}

// Use the first non-loopback IP (usually the right one)
const selectedIP = localIPs[0].address;

console.log(`\n✅ Using IP address: ${selectedIP}`);

// Step 2: Update .env.production
const proxyURL = `http://${selectedIP}:3001/api/claude`;
const envContent = `# Production environment variables
# Auto-generated by deploy-tablet.js
# Computer IP: ${selectedIP}
VITE_PROXY_URL=${proxyURL}
`;

try {
  writeFileSync('.env.production', envContent);
  console.log(`\n✅ Updated .env.production with proxy URL: ${proxyURL}`);
} catch (error) {
  console.error('\n❌ Error updating .env.production:', error.message);
  process.exit(1);
}

// Step 3: Build the application
console.log('\n📦 Building production version...');
console.log('   This may take a minute...\n');

try {
  execSync('npm run build', { stdio: 'inherit' });
  console.log('\n✅ Build completed successfully!');
} catch (error) {
  console.error('\n❌ Error building application:', error.message);
  process.exit(1);
}

// Step 4: Provide instructions
console.log('\n' + '='.repeat(50));
console.log('\n🎉 Deployment Preparation Complete!\n');
console.log('📱 TABLET ACCESS INSTRUCTIONS:\n');
console.log('1. Start the PROXY SERVER (Terminal 1):');
console.log('   cd app-new');
console.log('   npm run proxy\n');
console.log('2. Start the WEB SERVER (Terminal 2):');
console.log('   cd app-new');
console.log('   npx vite preview --host 0.0.0.0 --port 5000\n');
console.log('3. On your TABLET (same Wi-Fi network):');
console.log(`   Open: http://${selectedIP}:5000\n`);
console.log('='.repeat(50));
console.log('\n💡 TIP: Keep both terminals running while testing on tablet');
console.log('⚠️  Make sure your firewall allows connections on ports 3001 and 5000\n');
